on:
  push: # runs on every push
  pull_request: # runs on every PR

jobs:
  build-lint-test:
    name: Building, linting and testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run format:check
      - run: npm run test
  publish:
    name: Release • npm publish
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22.11.0 (LTS for publishing)
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          registry-url: https://registry.npmjs.org/
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
